### ISSUE TITLE
收集用户需求： 是否要支持电信短信协议SMGP

### ISSUE THREAD

**Issue by Lihuanghe** [Lihuanghe/CMPPGate#10]
需要支持电信协议SMGP的请留言。

目前cmppgate已经支持的短信协议有： 
cmpp , 移动
sigp,  联通
smpp

**Comment by sun1534** [comment]
通道引入时需要smgp协议，
对客户来讲 提供smgp协议给他用处不大

**Comment by shenbururen** [comment]
不能歧视电信不是。

**Comment by Lihuanghe** [comment]
不是歧视啊，是没需求啊

**Comment by Dolemi** [comment]
必须做，

**Comment by BailinSong** [comment]
需要看这个项目的定义 如果单纯以短信协议包或短信开发包来说 SMGP是不可或缺的，
 smpp国际/短信中心、cmpp移动、sgip联通，都已经实现了，但却唯独缺少SMGP电信，有些不能理解，,从项目功能定义上引入SMGP以保证项目的功能完整。另外其中彩信以有些鸡肋，而且增加了部分代码及第三方引入,如果可以的话单独迁出一个项目可能会更好。

**Comment by Lihuanghe** [comment]
@BailinSong 有道理，准备增加SMGP协议。

**Comment by zhanganshou** [comment]
需要，这样就三网齐全了

**Comment by Lihuanghe** [comment]
新增了SMGP协议支持
