### ISSUE TITLE
commons-codec  什么时候升级

### ISSUE THREAD

**Issue by zhanghaohaoa** [Lihuanghe/CMPPGate#20]
commons-codec  什么时候升级成最新版本

**Comment by Lihuanghe** [comment]
为什么要升这个？

**Comment by Lihuanghe** [comment]
不会升级到1.12,因为要支持java6

**Comment by zhanghaohaoa** [comment]
建议分开两个版本，一个是支持jdk6的，一个是支持最新版本的
netty也有升级最新版本，commons-codec 1.12去掉了一个方法，只能引入commons-codec1.11，让我很无奈

**Comment by zhanghaohaoa** [comment]
非常感谢你的分享，我只是提个建议，希望这个项目能越做越好

**Comment by zhanghaohaoa** [comment]
另外  SMGPSubmitMessage 没有 attachment 属性，是我没有找到吗？
