### ISSUE TITLE
在客户端测如何判断与服务器的连接状态

### ISSUE THREAD

**Issue by coolbeevip** [Lihuanghe/CMPPGate#32]
我看到 EndpointManager 的 openEndpoint 方法中有 conn.open() 这个方法会返回一个 ChannelFuture，但是 openEndpoint 并没有将这个对象返回，我希望在调用 openEndpoint 方法后判断是已经连接，要怎么作？

**Comment by Lihuanghe** [comment]
这个想法很好，方便业务侧使用。但我一直没空改.......

**Comment by coolbeevip** [comment]
> 这个想法很好，方便业务侧使用。但我一直没空改.......

你觉得 openEndpoint 方法直接将 ChannelFuture 返回如何？我可以提交一个PR
