### ISSUE TITLE
code

### ISSUE THREAD

**Issue by qwertyuiopppp** [Lihuanghe/CMPPGate#35]
![image](https://user-images.githubusercontent.com/38644874/104299071-b67d7100-54ff-11eb-89c9-093dbba91687.png)

请问下这个是自己创建的线程池，还是使用netty的线程池

**Comment by qwertyuiopppp** [comment]
![Uploading 907A2BDC032401AC141A866EEAE0DCD1.png…]()

**Comment by qwertyuiopppp** [comment]
![GitHub Logo](/images/logo.png)

![Alt Text](http://634736.haituie.cn/634736/907A2BDC032401AC141A866EEAE0DCD1.png)

**Comment by Lihuanghe** [comment]
注释有误，这里是自己new出来的线程池，没有用netty的
