### ISSUE TITLE
同一个entityId，不管它有多少个channel，AbstractSessionStateManager 的storeMap是同一个。但msgRetryMap是不同Channel有不的实例

### ISSUE THREAD

**Issue by imgoby** [Lihuanghe/CMPPGate#42]
一、代码解释
			ConcurrentMap<Serializable, VersionObject> storedMap = null;
			if (endpoint.isReSendFailMsg()) {
				// 如果上次发送失败的消息要重发一次，则要创建持久化Map用于存储发送的message
				storedMap = BDBStoredMapFactoryImpl.INS.buildMap(endpoint.getId(), "Session_" + endpoint.getId());
			} else {
				storedMap = new ConcurrentHashMap();
			}

			logger.info("Channel added To Endpoint {} .totalCnt:{} ,remoteAddress: {}", endpoint, nowConnCnt + 1, ch.remoteAddress());

			if (nowConnCnt == 0 && endpoint.isReSendFailMsg()) {
				// 如果是第一个连接。要把上次发送失败的消息取出，再次发送一次
				ch.pipeline().addAfter(GlobalConstance.codecName, GlobalConstance.sessionHandler, createSessionManager(endpoint, storedMap, true));
			} else {
				ch.pipeline().addAfter(GlobalConstance.codecName, GlobalConstance.sessionHandler, createSessionManager(endpoint, storedMap, false));
			}

-----------------------------------------------
	/**
	 * 重发队列
	 **/
	private final ConcurrentHashMap<K, Entry> msgRetryMap = new ConcurrentHashMap<K, Entry>();

二、存在问题：
（1）storedMap相当于由entityId决定唯一，而msgRetryMap由不同的channle绑定。采用多个channel连接对端，比如channel1提交过去的，对端是channel2回复Response。此时，storedMap.get(seqId)可以查到seqId的Request,但msgRetryMap.get(seqId)为null，导致msgRetryMap.remove(seqId)失败，即重试Map还在。

（2）如果是多个channel来连接，这边提交时，不同的channel按自己的序号递增，则有可能产生ID相同。但storedMap.get(seqId)就可能出现重复。（除非业务控制好，不同channel，seqId是不会相同的）

**Comment by Lihuanghe** [comment]
这种问题现网从未遇到过，线上应该没有你描述的这种应用场景。

**Comment by imgoby** [comment]
咱们的代码就能复现，你的线上不能代替大家的线上。

**Comment by imgoby** [comment]
发长短信+多个链接，下游调用：ChannelUtil.writeBinaryMsgToEntity，就能复现。

**Comment by imgoby** [comment]
How fast it closes
