### ISSUE TITLE
短信网关集群收到客户的请求，怎么知道发送客户ID和账号ID？

### ISSUE THREAD

**Issue by xhyan0427** [Lihuanghe/CMPPGate#46]
根据 
智能应答基本流程图 https://www.processon.com/view/link/598c16ace4b02e9a26eeed11，短信网关集群收到客户的请求后，怎么知道发送客户ID和账号ID是多少啊，要怎么获取啊？

**Comment by Lihuanghe** [comment]
AbstractBusinessHandler 里有getEndpointEntity（）方法。
或者 ctx.channel().attr(GlobalConstance.entityPointKey).get();也可以获取
