### ISSUE TITLE
作为短信客户端应该怎么使用？

### ISSUE THREAD

**Issue by gaoyili** [Lihuanghe/CMPPGate#9]
如题，作为SP端发送和接收短信，没看太明白怎么使用？

**Comment by Lihuanghe** [comment]
这是一个基于netty的短信框架，需要先熟悉netty的用法。
发送和接收短信都是在netty的channelHandler里处理的。这跟一般的java库的调用方法不同，需要先写netty的channelHandler来处理网络上收发数据。
